### ISSUE TITLE
Crashing for Unreal 4.19.2

### ISSUE THREAD

**Issue by Derekioh** [leapmotion/LeapUnreal#4] opened 2018-06-22 18:44 UTC
Hey There.

I have created a blank project in unreal 4.19.2, downloaded the newest plugin from the Release section, and moved the Plugin folder into the root of my project and restarted unreal. When try using LeapHandsPawn example, however, after a few times of Play mode it crashes.

**Comment by getnamo** [comment] 2018-06-24 14:06
Does tracking work at all? When do you have a log of the crashes that are occurring? Does it crash on begin play or ending it? Anything you can provide will help me reproduce the bug.

**Comment by Derekioh** [comment] 2018-06-24 14:14
Tracking works...sort of. The hands are often times flipped left and right, as well as the hand is flipped upside down. The finger tracking suffers from this as a result. The UE4 was not producing a log, which I thought was strange. It can happen at various times, but mostly after ending it. Let me see if I can pin point more accurately it crashes.

**Comment by Derekioh** [comment] 2018-06-24 14:14
I have also tried using both desktop and HeadMounted Mode, doesnt seem to matter which I use.

**Comment by Derekioh** [comment] 2018-06-24 14:51
And now I have tried your Leap Modules that you created here: https://github.com/leapmotion/LeapUnrealModules
And had the UE4 crash during Play Mode after I started the Debug module, ended it, then switched to Hello World VR. Here is the crash folder.

I hope this helps!
[crash2.zip](https://github.com/leapmotion/LeapUnreal/files/2130878/crash2.zip)

**Comment by getnamo** [comment] 2018-06-24 15:30
note to self: dump seems to point at 

https://github.com/leapmotion/LeapUnreal/blob/master/Source/BodyState/Private/AnimNode_ModifyBodyStateMappedBones.cpp#L32 with ```CompactPoseBoneToModify```, BoneIndex == 2 . 

with assert ```"!Pose[ParentIndex].ContainsNaN()"``` on ```GetComponentSpaceTransform```

**Comment by Derekioh** [comment] 2018-06-24 15:50
Yes, i have v4 driver installed.

**Comment by getnamo** [comment] 2018-06-25 02:12
Note to self: confirmed replication, likely due to anythread evaluation, I'm doing something not threadsafe

**Comment by getnamo** [comment] 2018-06-25 03:01
added potential fix in https://github.com/leapmotion/LeapUnreal/commit/6bb9528e036d2dac67de6081c85301ea6f608ec3, waiting for https://github.com/leapmotion/LeapUnreal/issues/5 and https://github.com/leapmotion/LeapUnreal/issues/6 before cleaning up and making new release.

**Comment by gouzibaobao** [comment] 2018-06-25 13:30
it was so terrible to package a project using the engine's default leap motion content. 
Everything was ok when in editor,but i can.t packaget the leap motion into my project.
i add a c++ blank code as the documents and video told me, 
I add the code to enable plugin =leap motion in root/config/default engine.ini  
and alse i tried to make installed true in .uplugin,and so on~
really ,it still not work ,i have already spend three whole days to solve this problem. but owned nothing.
it makes me tired.
the only way it works is to download theDownload latest release (make sure to use the .7z link),ti works ,and can package int project .

but， i use the engine's default leap motion plugin  did all the functions,it takes me almost a month.  there is no time to change to the latest plugin, it makes me feel so terrible~

is it really don‘t have a way to package the project within the unreal engine's default plugin?
what the steps to do it ?
i am realy want to know it as soon as possible ~

**Comment by getnamo** [comment] 2018-06-25 14:09
@gouzibaobao Your question is not related to this issue and since you are asking about the old v2 plugin, please open it at the old plugin issues https://github.com/getnamo/leap-ue4/issues. Note that going forward the old plugin is deprecated and this plugin replaces it.

The new architecture is more flexible and should make it vastly easier to get what you want working.

**Comment by getnamo** [comment] 2018-07-21 00:02
addressed in https://github.com/leapmotion/LeapUnreal/releases/tag/v3.0.0

**Closed by getnamo** 2018-07-21 00:02 UTC
Labels: addressed waiting release, bug
