### ISSUE TITLE
BodyStateAnimInstance Crashes Editor

### ISSUE THREAD

**Issue by BaazarProductions** [leapmotion/LeapUnreal#39] opened 2019-03-19 07:58 UTC
Revisiting this unanswered question. Reparenting the Anim Blueprint for any of my custom figures cause the editor to crash. The only one that seems to work is the Mannequin. Thank you! Let me know what else I can provide.

**Comment by getnamo** [comment] 2019-04-24 04:31
Duplicate of https://github.com/leapmotion/LeapUnreal/issues/17. Current work around disables auto-detection by default: https://github.com/leapmotion/LeapUnreal/commit/77a403f36e182cefa2052c261494c78dfb7ef15f which enables you to manually map your bones. Looking to fix the auto-mapping for the wider skeletal meshes after https://github.com/leapmotion/LeapUnreal/issues/31.

**Closed by getnamo** 2019-04-24 04:31 UTC
Labels: duplicate
